# Generated by Django 5.0.6 on 2024-10-02 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_story_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='created_at',
            new_name='created_on',
        ),
    ]
